name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  actionlint:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true

  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@v1.30.0
        with:
          files: "*.md src/ scripts/ .github/"

  shellcheck:
    name: Shell Script Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: "-i 2"  # Use 2 spaces (matches pre-commit config)
        with:
          sh_checker_comment: false
          sh_checker_exclude: ".git"

  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run Ruff linter
        run: uv run ruff check src/ scripts/

      - name: Run Ruff formatter check
        run: uv run ruff format --check src/ scripts/

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run mypy
        run: uv run mypy src/ scripts/
        continue-on-error: true  # Don't fail CI on type errors yet

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run tests
        run: uv run pytest --cov=src --cov-report=term-missing
        continue-on-error: true  # Don't fail until tests exist
